### ISSUE TITLE
DS-2019

### ISSUE THREAD

**Issue by jorondo1** [mblstamps/stamps2022#2]
Hi,
I will be coming in from Canada and was wondering if I need a Certificate of Eligibility, the course being taught at a university. From [this page](https://ca.usembassy.gov/visas/canadian-students/) I am not sure if I will need one to cross the border, but I wanted to see if you have any prior experience with this.

Thanks in advance,
Jonathan

**Comment by ctb** [comment]
hi @jorondo1 please contact Carol Hamel, [chamel@mbl.edu](mailto:chamel@mbl.edu).

**Comment by ctb** [comment]
(she will know for sure, and she can provide you with such a certificate if it is needed!)

**Comment by jorondo1** [comment]
thanks a lot !

**Comment by NoGaud** [comment]
Hi, did you have a final answer? I'm from Canada too, but i don't really know about this. 

Thanks!

**Comment by tracykteal** [comment]
That's something that the MBL folks have information about, so it's best to contact them directly. You can email Carol Hamel to help!

**Comment by jorondo1** [comment]
@NoGaud if you give me your email I can forward you the answer Carol sent me!
